server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /robots.txt {
        default_type text/plain;
        try_files /robots.txt =404;
    }

    location = /sitemap.xml {
        default_type application/xml;
        try_files /sitemap.xml =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
